### PR TITLE
WAZO-3250: use `selectinload` eagerloading startegy to accelerate user query

### PR DESCRIPTION
**Pull request by ja0x**
Why:
* Allows to eagerload results resulting in performance gain versus lazy (which is used by default)

Results with a 1605 users stack w/o change: ~3.6 seconds
Results with a 1605 users stack w/ change: ~500ms

---
To test, mount code and measure execution time on GET `/users/presence?recurse=True`

### CODE REVIEW

**Comment by ja0x** [comment]
Should be fixed by https://github.com/wazo-platform/wazo-test-helpers/pull/86

**Comment by ja0x** [comment]
Should be fixed by https://github.com/wazo-platform/wazo-test-helpers/pull/86

**Comment by ja0x** [comment]
recheck

**Review by fblackburn1 — CHANGES_REQUESTED** [review]
Can you add a simple test to avoid to have same issue if we refactor? (ex: calculate number of request (ref confd))

**Comment by pc-m** [comment]
After a year without any traction I consider that this is not required anymore

**Pull request closed without merging**
