### PR TITLE
Pull request for WAZO-1319-add-connected-attribute

### PR DESCRIPTION
**Pull request by fblackburn1**
Depends-on: https://github.com/wazo-platform/wazo-chatd/pull/33

### CODE REVIEW

**Comment by fblackburn1** [comment]
recheck

**Comment by pc-m** [comment]
Hi @fblackburn1, this PR has not seen any attention for a while. Is it still valid?

**Comment by fblackburn1** [comment]
> Hi @fblackburn1, this PR has not seen any attention for a while. Is it still valid?

Yes absolutely, we wait on compatibility matrix with stack-apps. Some meeting have been done, but I don't think any concrete action are done

**Comment by sduthil** [comment]
recheck

**Review by pc-m — APPROVED** [review]

**Pull request merged**
